### PR TITLE
Fix compile failure with non-cargo build systems

### LINKED ISSUE #22: Compile failure with non-cargo build systems
The following line fails to compile with non-cargo build systems, like Bazel.

https://github.com/taiki-e/const_fn/blob/9383c4a2d815e6d25802cff4848e7a7b350c4e1d/src/lib.rs#L211

Non-version-based code generation (`const_fn(cfg)`, `const_fn(feature)`) does not actually need build-scripts, so compile should not fail even if you are using those build systems.
Version-based code generation needs build-scripts, but if used with these build-systems, we should probably always generate normal functions. (This is basically the same behavior as when outputting cfg by build-scripts.)

### PR DESCRIPTION
**Pull request by taiki-e**
Fixes #22

### CODE REVIEW

File: build.rs [hunk 1]
```diff
@@ -1,6 +1,8 @@
 use std::{env, fs, path::PathBuf};
 
 fn main() {
+    println!("cargo:rustc-cfg=const_fn_has_build_script");
```
Comment (taiki-e) [inline build.rs:4]: This is like a marker that means "build-script was run". If the build-script was run, but the output of the build-script is broken, you should get an error.
